name: CI/CD Pipeline for Python app
on:
    push:
        branches:
            - main
        paths:
            - src/**

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            -   name: Login to Docker hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Shorten commit_id
                shell: bash
                run: |
                    echo "COMMIT_ID=${GITHUB_SHA::6}" >> ${GITHUB_ENV}
            
            -   name: Docker Build and Push
                uses: docker/build-push-action@v6
                with:
                    push: true
                    tags: aumthakkar/pyapp-5:${{ env.COMMIT_ID }}

        outputs:
            commit_id: ${{ env.COMMIT_ID }}

    cd:
        runs-on: self-hosted
        needs: ci
        steps:
            -   name: Checkout Github Repo
                uses: actions/checkout@v6

            -   name: Update tag in values.yaml file
                run: |
                    sudo apt update && sudo apt install python3-pip -y
                    pip install yq --break-system-packages
                    echo "${{ needs.ci.outputs.commit_id }}"
                    yq -Yi '.image.tag = "${{ needs.ci.outputs.commit_id }}"' charts/py5app/values.yaml

            -   name: Commit Change
                uses: EndBug/add-and-commit@v9
                with:
                    message: "pushed the image with tag: ${{ needs.ci.outputs.commit_id }}"

            -   name: Install ArgoCD CLI
                run: |
                    curl -ksSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/v3.2.2/download/argocd-linux-amd64
                    sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
                    rm argocd-linux-amd64

            -   name: ArgoCD login and Sync app with ArgoCD
                run: |
                    argocd login argocd-server.argocd \
                    --grpc-web \
                    --insecure \
                    --username ${{ secrets.ARGOCD_USERNAME }}
                    --password ${{ secrets.ARGOCD_PASSWORD }}

                    argocd app sync py5app







                

