name: CI/CD Pipeline for Python app
on:
    push:
        branches:
            - main
        paths:
            - src/**

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            -   name: Login to Docker hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Shorten commit_id
                shell: bash
                run: |
                    echo "COMMIT_ID=${GITHUB_SHA ::6}" >> ${GITHUB_ENV}
            
            -   name: Docker Build and Push
                uses: docker/build-push-action@v6
                with:
                    push: true
                    tags: aumthakkar/pyapp-5:${{ env.COMMIT_ID }}

        outputs:
            commit_id: ${{ env.COMMIT_ID }}